---
abstract: 'Retrieve Anime info. with SyoboiCalendar API.'
author:
  - 'Yohei Fushii <hakobe@gmail.com>'
build_requires:
  Data::Section::Simple: 0
  LWP::Protocol::PSGI: 0
  Router::Simple: 0
  Test::More: 0
  Test::use::ok: 0
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.11.0, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-SyoboiCalendar
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  WebService::SyoboiCalendar:
    file: lib/WebService/SyoboiCalendar.pm
    version: 0.01
  WebService::SyoboiCalendar::API:
    file: lib/WebService/SyoboiCalendar/API.pm
  WebService::SyoboiCalendar::API::Result:
    file: lib/WebService/SyoboiCalendar/API/Result.pm
  WebService::SyoboiCalendar::API::Search:
    file: lib/WebService/SyoboiCalendar/API/Search.pm
  WebService::SyoboiCalendar::Error:
    file: lib/WebService/SyoboiCalendar/Error.pm
  WebService::SyoboiCalendar::Program:
    file: lib/WebService/SyoboiCalendar/Program.pm
  WebService::SyoboiCalendar::Title:
    file: lib/WebService/SyoboiCalendar/Title.pm
recommends:
  Config::Pit: 0
  Eval::WithLexicals: 0
  Term::ANSIColor::Markup: 0
  Term::Encoding: 0
  Text::Xslate: 0
  YAML: 0
requires:
  DateTime: 0
  Encode: 0
  Exception::Class: 0
  JSON::XS: 0
  LWP::UserAgent: 0
  Moo: 0
  Readonly: 0
  Regexp::Common: 0
  Smart::Args: 0.08
  URI: 0
  Web::Query: 0
  perl: 5.008001
resources:
  bugtracker: https://github.com/hakobe/WebService-SyoboiCalendar/issues
  homepage: https://github.com/hakobe/WebService-SyoboiCalendar
  repository: git://github.com/hakobe/WebService-SyoboiCalendar.git
version: 0.01
